# Generated by Django 2.2.16 on 2022-04-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220405_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Укажите группу публикации', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g_posts', to='posts.Group', verbose_name='Группа публикации'),
        ),
    ]
