# Generated by Django 2.2.16 on 2022-04-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
