# Generated by Django 2.2.16 on 2022-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220412_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите текст комментария', max_length=1000, verbose_name='Текст комментария'),
        ),
    ]
